openapi: 3.0.3

info:
    title: ComUnica to FrontOffice SUAP

    version: 1.0.0

    description: |-
        API rese disponibili da ComUnica a FrontOffice SUAP

    contact:
        name: AgID - Agenzia per l'Italia Digitale
        url: https://www.agid.gov.it/

    license:
        name: CC BY-NC-SA 4.0
        url: https://creativecommons.org/licenses/by-nc-sa/4.0/

servers:
    - url: https://<system host+subdomains>.it
      description: ComUnica to FrontOffice SUAP endpoint

paths:
    /retry:
        post:
            description: Richiesta di ritrasmissione dati relativi ad una specifica operation a causa di incoerenze riscontrate sui dati ricevuti.
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                cui:
                                    $ref: "#/components/schemas/cui"
                                operation:
                                    description: operation per la quale si richiede la ritrasmissione
                                    type: string
                                    enum:
                                        - notify_receipt
                                        - cancel_instance
                                error:
                                    $ref: "#/components/schemas/Error"

            responses:
                "200":
                    $ref: "#/components/responses/OKRequest"
                "400":
                    $ref: "#/components/responses/BadRequest"
                "401":
                    $ref: "#/components/responses/Unauthorized"
                "500":
                    $ref: "#/components/responses/ServerError"
                "503":
                    $ref: "#/components/responses/ServiceUnavaliable"

            security:
                - bearerAuth: []
                  Agid-JWT-Signature: []

    /send_instance:
        description: Invio riferimenti istanza
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SendInstanceRequest"
                required: true
            responses:
                "200":
                    $ref: "#/components/responses/OKRequest"
                "400":
                    $ref: "#/components/responses/BadRequest"
                "401":
                    $ref: "#/components/responses/Unauthorized"
                "500":
                    $ref: "#/components/responses/ServerError"
                "503":
                    $ref: "#/components/responses/ServiceUnavaliable"
            security:
                - bearerAuth: []
                  Agid-JWT-Signature: []

components:
    responses:
        OKRequest:
            description: Richiesta completata con successo
            headers:
                Agid-JWT-Signature:
                    $ref: "#/components/headers/Agid-JWT-Signature"

        BadRequest:
            description: Forma della richiesta non conforme alla specifica
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
            headers:
                Agid-JWT-Signature:
                    $ref: "#/components/headers/Agid-JWT-Signature"
        ServiceUnavaliable:
            description: Servizio non disponibile
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
            headers:
                Agid-JWT-Signature:
                    $ref: "#/components/headers/Agid-JWT-Signature"

        Unauthorized:
            description: Richiesta non autorizzata
            headers:
                Agid-JWT-Signature:
                    $ref: "#/components/headers/Agid-JWT-Signature"
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
        ServerError:
            description: Errore processamento richiesta
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
            headers:
                Agid-JWT-Signature:
                    $ref: "#/components/headers/Agid-JWT-Signature"

    schemas:
        cui:
            type: object
            description: codice unico dell'istanza
            required:
                - context
                - data
                - progressive
                - uuid
            properties:
                context:
                    title: contesto dell'istanza
                    type: string
                data:
                    title: data emissione cui
                    type: string
                    format: date
                
                progressivo:
                    title: numero progressivo a rotazione annuale
                    type: string

                uuid:
                    title: UUID chiave del CUI
                    type: string
        
        InstanceIndex:
            type: array
            description: indice istanza
            items:
                type: object
                required:
                - code
                - ref
                - resource_id
                - hash
                - alg_hash
                properties:
                    code:                            
                        title: codice della fattispecie presente nel Catalogo
                        type: string
                        minLength: 1
                    ref:                            
                        title: riferimento all'elemento dell'istanza relativo al procedimento
                        type: string
                        minLength: 1
                    resource_id:                            
                        title: id della risorsa, univoco per erogatore e CUI.UUID
                        type: string
                        minLength: 1
                    hash:                            
                        title: hash dell'elemento dell'istanza relativo al procedimento
                        type: string
                        minLength: 1
                    alg_hash:                                
                        title: algoritmo hash applicato
                        type: string
                        enum:
                        - S256
                        - S384
                        - S512
        GeneralIndex:
            type: array
            description: indice allegati trasversali
            items:
                type: object
                required:
                - type
                - resource_id
                - hash
                - alg_hash
                properties:
                    type:                            
                        title: tipologia di allegato trasversale alle fattispecie
                        type: string
                        enum:
                        - RICEVUTA_XML
                        - RICEVUTA_PDF
                        - SUAP_XML
                        - SUAP_PDF
                        - SUAP_REA_START_XML
                        - SUAP_REA_UPDATE_XML
                        - SUAP_REA_END_XML
                        - COMUNICA_CUI_XML
                        - COMUNICA_CUI_PDF
                        minLength: 1
                    resource_id:                            
                        title: id della risorsa, univoco per erogatore e CUI.UUID
                        type: string
                        minLength: 1
                    hash:                            
                        title: hash dell'elemento dell'istanza relativo al procedimento
                        type: string
                        minLength: 1
                    alg_hash:                                
                        title: algoritmo hash applicato
                        type: string
                        enum:
                        - S256
                        - S384
                        - S512
        Error:
            type: object
            description: codice e descrizione condizione di errore
            properties:
                code:
                    type: string
                message:
                    type: string
            required:
                - code
                - message
        SendInstanceRequest:
            required:
                - cui
                - instance_descriptor_version
                - instance_code_comunica
                - instance_index
                - general_index
            type: object
            properties:
                cui:
                    $ref: "#/components/schemas/cui"
                instance_descriptor_version:
                    type: string
                instance_code_comunica:
                    type: string
                instance_index:
                    $ref: "#/components/schemas/InstanceIndex"
                general_index:
                    $ref: "#/components/schemas/GeneralIndex"

    headers:
        Agid-JWT-Signature:
            schema:
                format: JWS
                maxLength: 4096
                type: string
                example: eyJzd.fafa.fafafa
            description: |-
                Il valore di questo header è una token JWT firmato secondo la specifica JWS.
                Vedi Modi  [integrity_rest_01] Integrità del payload del messaggio REST.

    securitySchemes:
        bearerAuth:
            scheme: bearer
            bearerFormat: JWT
            type: http
            description: Implementazione conforme ad RFC8725

        Agid-JWT-Signature:
            type: apiKey
            description: |-
                Il valore di questo header è una token JWT firmato secondo la specifica JWS.
                Vedi Modi  [integrity_rest_01] Integrità del payload del messaggio REST.
            name: Agid-JWT-Signature
            in: header
