sequenceDiagram
    autonumber
    
    participant B as BackOffice SUAP  
    participant RI as Registro Imprese   
    participant C as Catalogo SSU  

   
   
    Note over B,C: istanza presentata e ricevuta emessa (dopo step 22 di General-001)
    

    B ->> RI: send_instance(SendInstanceRequest)
    RI -->> B: ack
    
    RI ->> C: request_instance_descriptor(cui)
	C -->> RI: instanceDescriptor
    
    loop per ogni procedimento parte dell'istanza
        RI ->> B:  request_instance_document(cui, resource_id)
        note right of RI: resource_id da instance_index
        B -->> RI: instanceDocument
    end

    B ->> C: audit(cui, instance_to_ri_sended)
    C -->> B: ack
    

    alt istanza corretta (dopo step 43 General-001)

        B ->> RI: send_instance(SendInstanceRequest)
        RI -->> B: ack
    
        RI ->> C: request_instance_descriptor(cui)
        C -->> RI: instanceDescriptor
        
        loop per ogni procedimento parte dell'istanza
            RI ->> B:  request_instance_document(cui, resource_id)
            note right of RI: resource_id da instance_index
            B -->> RI: instanceDocument
        end

        B ->> C: audit(cui, corrected_instance_to_ri_sended)
        C -->> B: ack

    end

    alt istanza integrata o conformata (dopo step: 45 SCIA-001 o 65 DomandaAutorizzazione-001 o dopo step 65, 143 di SCIA Condizionata)

        alt:
            B ->> RI: send_conformation_documents(SendUpdatedDocuments)
        else:
            B ->> RI: send_integration_documents(SendUpdatedDocuments)
        end
        RI -->> B: ack
    
        RI ->> C: request_instance_descriptor(cui)
        C -->> RI: instanceDescriptor
        
        loop per ogni procedimento parte dell'istanza
            RI ->> B:  request_instance_document(cui, resource_id)
            note right of RI: resource_id da updated_documents
            B -->> RI: instanceDocument
        end

        alt Istanza conformata
            B ->> C: audit(cui, instance_conformated_to_ri_sended)
            C -->> B: ack
        else Instanza integrata
            B ->> C: audit(cui, instance_integrated_to_ri_sended)
            C -->> B: ack
        end

    end

    alt invio dei motivi ostativi (dopo step: 90 DomandaAutorizzazione-001 o 90 SCIA Condizionata)
        B ->> RI: notify(cui, instance_descriptor_version, existence_of_impediments, resource_id)
        RI -->> B: ack
        RI ->> B:  request_instance_document(cui, resource_id)
        note right of RI: resource_id da notify
        B -->> RI: instanceDocument
    end

    alt risposta ai motivi ostativi (dopo step: 95 DomandaAutorizzazione-001 o 95 SCIA Condizionata)
        B ->> RI: notify(cui, instance_descriptor_version, observations_to_impediments_provided, resource_id)
        RI -->> B: ack
        RI ->> B:  request_instance_document(cui, resource_id)
        note right of RI: resource_id da notify
        B -->> RI: instanceDocument
        B ->> C: audit(cui, observations_to_impediments_provided_to_RI)
        C -->> B: ack
    end

    alt richiesta integrazione presentata e scaduti tempi integrazione (dopo step: 56 DomandaAutorizzazione-001 o 56 SCIA Condizionata)

        B ->> RI: notify(cui, instance_descriptor_version, end_by_integration_times_expired)
        RI -->> B: ack

    else richiesta di conformazione presentata e scaduti i tempi di conformazione (dopo step: 36 SCIA-001 o 134 SCIA Condizionata)
    
        B ->> RI: notify(cui, instance_descriptor_version, end_by_conformation_times_expired)
        RI -->> B: ack

    else chiusura istruttoria con esito positivo (dopo step: 133 DomandaAutorizzazione-001 o 197 SCIA Condizionata)

        B ->> RI: notify(cui, instance_descriptor_version,end_by_positive_outcome,resource_id)
        RI -->> B: ack

        RI ->> B: request_instance_document(cui, resource_id)
        B -->> RI: instanceDocument 

    else chiusura istruttoria con esito negativo (dopo step: 144 DomandaAutorizzazione-001 208 SCIA Condizionata)

        B ->> RI: notify(cui, instance_descriptor_version,end_by_negative_outcome,resource_id)
        RI -->> B: ack

        RI ->> B: request_instance_document(cui, resource_id)
        B -->> RI: instanceDocument 

    else chiusura istruttoria per sospensione (dopo step: 70 SCIA-001)

        B ->> RI: notify(cui, instance_descriptor_version,end_by_suspension_requested,resource_id)
        RI -->> B: ack

        RI ->> B: request_instance_document(cui, resource_id)
        B -->> RI: instanceDocument 

    end
