sequenceDiagram
    autonumber
    
    participant B as BackOffice SUAP  
    participant RI as Registro Imprese   
    participant C as Catalogo SSU  

   
   
    Note over B,C: istanza presentata e ricevuta emessa (dopo step 22 di General-001)
    

    B ->> RI: send_instance(SendInstanceRequest)
    RI -->> B: ack
    
    RI ->> C: request_instance_descriptor(cui)
	C -->> RI: instanceDescriptor
    
    loop per ogni procedimento parte dell'istanza
        RI ->> B:  request_instance_document(cui, resource_id)
        note right of RI: resource_id da instance_index
        B -->> RI: instanceDocument
    end
    

    alt istanza corretta (dopo step 43 General-001)

        B ->> RI: send_instance(SendInstanceRequest)
        RI -->> B: ack
    
        RI ->> C: request_instance_descriptor(cui)
        C -->> RI: instanceDescriptor
        
        loop per ogni procedimento parte dell'istanza
            RI ->> B:  request_instance_document(cui, resource_id)
            note right of RI: resource_id da instance_index
            B -->> RI: instanceDocument
        end



    end

    alt istanza integrata o conformata (dopo step: 43 SCIA-001 o 96 SCIA-001  o 63 DomandaAutorizzazione-001)

        B ->> RI: send_instance(SendInstanceRequest)
        RI -->> B: ack
    
        RI ->> C: request_instance_descriptor(cui)
        C -->> RI: instanceDescriptor
        
        loop per ogni procedimento parte dell'istanza
            RI ->> B:  request_instance_document(cui, resource_id)
            note right of RI: resource_id da instance_index
            B -->> RI: instanceDocument
        end


    end

    alt richiesta integrazione e scaduti tempi integrazione (dopo step: 29 SCIA-001 o 49 DomandaAutorizzazione-001)

        B ->> RI: notify(cui, instance_descriptor_version,end_by_integration_times_expired)
        RI -->> B: ack

    else richiesta di conformazione e scaduti i tempi di conformazione (dopo step: 87 SCIA-001)
    
        B ->> RI: notify(cui, instance_descriptor_version, end_by_conformation_times_expired)
        RI -->> B: ack

    else chiusura istruttoria con esito positivo (dopo step: 69 SCIA-001 o 112 DomandaAutorizzazione-001)

        B ->> RI: notify(cui, instance_descriptor_version,end_by_positive_outcome,resource_id)
        RI -->> B: ack

        RI ->> B: request_instance_document(cui, resource_id)
        B -->> RI: instanceDocument 

    else chiusura istruttoria con esito negativo (dopo step: 105 DomandaAutorizzazione-001)

        B ->> RI: notify(cui, instance_descriptor_version,end_by_negative_outcome,resource_id)
        RI -->> B: ack

        RI ->> B: request_instance_document(cui, resource_id)
        B -->> RI: instanceDocument 

    else chiusura istruttoria per sospensione (dopo step: 76 SCIA-001)

        B ->> RI: notify(cui, instance_descriptor_version,end_by_suspension_requested,resource_id)
        RI -->> B: ack

        RI ->> B: request_instance_document(cui, resource_id)
        B -->> RI: instanceDocument 

    else chiusura istruttoria per conformazione con esito positivo (dopo step: 121 SCIA-001)

        B ->> RI: notify(cui, instance_descriptor_version, end_by_positive_conformation)
        RI -->> B: ack

    else chiusura istruttoria per conformazione con esito negativo (dopo step: 128 SCIA-001)

        B ->> RI: notify(cui, instance_descriptor_version, end_by_negative_conformation,resource_id)
        RI -->> B: ack

        RI ->> B: request_instance_document(cui, resource_id)
        B -->> RI: instanceDocument 

    end
