
sequenceDiagram
    autonumber
    actor P as Presentatore    
    participant F as FrontOffice SUAP
    participant B as BackOffice SUAP   
    participant C as Catalogo SSU 
    participant E as Enti Terzi    
    Note over F,B: istanza procedibile
    alt Regime Amministrativo=AUTORIZZAZIONE,SCIA
        par per ogni ente terzo interessato        
            B ->> E: send_instance(SendInstanceRequest)
            E -->> B: ack
            B ->> C: audit(cui,instance_to_<ET>_sended)
            note right of B: <ET> codice ente terzo 
            C -->> B: ack
            E ->> C: request_instance_descriptor(cui)
            C -->> E: instanceDescriptor
            loop per ogni procedimento di interesse parte dell'istanza 
            E ->> B: request_instance_document(cui, resource_id)
            note left of E: resource_id da instance_index
            B -->> E: instanceDocument
            end
            E ->> C: audit(cui,instance_retrived_from_<ET>)
            C -->> E: ack
        end
    end
    alt Regime Amministrativo=AUTORIZZAZIONE | CdSS da SUAP AND SUAP ente procedente
        opt 
            B ->> C: request_update_times(cui,times)
            C -->> B: instanceDescriptor
        end 
        B ->> F: notify(cui, instance_descriptor_version,cdss_convened)
        F -->> B: ack    
        par per ogni ente terzo interessato
            B ->> E: notify(cui, instance_descriptor_version,cdss_convened)
            E -->> B: ack
        end
        
        B ->> C: audit(cui,cdss_convened)
        C -->> B: ack
       
    else Regime Amministrativo=AUTORIZZAZIONE,SCIA | No CdSS da SUAP
        alt Regime Amministrativo=AUTORIZZAZIONE | almeno un ET richiede CdSS entro i tempi
            par almeno un ente terzo
                E ->> B: request_cdss(cui, requester_administration)
                B -->> E: ack 
                E ->> C: audit(cui,cdss_requested_from_<ET>)
                C -->> E: ack           
            end
            opt 
                B ->> C: request_update_times(cui,times)
                C -->> B: instanceDescriptor
            end
            B ->> F: notify(cui, instance_descriptor_version,cdss_convened)
            F -->> B: ack    
            par per ogni ente terzo interessato
                B ->> E: notify(cui, instance_descriptor_version,cdss_convened)
                E -->> B: ack
            end
            B ->> C: audit(cui,cdss_convened)
            C -->> B: ack
        else Regime Amministrativo=AUTORIZZAZIONE | ET ente procedente AND CDSS da ET
            E ->> B: notify(cui,instance_descriptor_version,cdss_convened_from_<ET>)
            B -->> E: ack
            B ->> F: notify(cui, instance_descriptor_version,cdss_convened_from_<ET>)
            F -->> B: ack    
            par ET procedente convoca gli altri ET interessati
                E ->> E: notify(cui, instance_descriptor_version,cdss_convened_from_<ET>)
                E -->> E: ack
            end
            E ->> C: audit(cui,cdss_convened_from_<ET>)
            C -->> E: ack
        else Regime Amministrativo=AUTORIZZAZIONE,SCIA | CdSS no richiesta da ET
            opt Regime Amministrativo=AUTORIZZAZIONE | almeno una richiesta integrazione
                par almeno un ente terzo
                    E ->> B: request_integration(cui, instance_descriptor_version,integration_list,resource_id)
                    B -->> E: ack 
                    opt
                        B ->> E: request_instance_document(cui, resource_id)
                        note right of B: recupero documento di richiesta integrazione
                        E -->> B: instanceDocument    
                    end
                    alt Aggiunti allegati non presenti nell'instance descriptor
                        F ->> C: audit(cui, integration_requested_with_new_document_to_<Usecase_Proceding_Code>_from_<ET>)
                        C -->> F: ack
                    else
                        E ->> C: audit(cui,integration_requested_from_<ET>)
                        C -->> E: ack   
                    end        
                end
                alt concluso il tempo di richiesta integrazione 
                    par per ogni ente terzo
                        B ->> E: notify(cui, instance_descriptor_version, integration_request_time_expired)
                        E -->> B: ack
                    end
                    B ->> C: audit(cui, integration_request_time_expired)
                    C -->> B: ack
                end 
                Note over B: concluso il tempo di richiesta integrazione OR tutti gli enti terzi hanno richiesto integrazione
                B ->> F: request_integration(cui, instance_descriptor_version,list_of_integration_list,integration_document_list)
                F -->> B: ack
                alt Aggiunti allegati non presenti nell'instance descriptor
                    F ->> C: audit(cui, integration_requested_with_new_document_to_<Usecase_Proceding_Code>_from_<ET>)
                    C -->> F: ack
                else
                    B ->> C: audit(cui,integration_requested)
                    C -->> B: ack
                end
                B ->> C: request_update_times(cui,times)
                Note right of B: Aggiorna i tempi procedimentali incrementantoli di X giorni, dove X è max_gg_int_resp dell'oggetto Times
                C -->> B: instanceDescriptor
                opt
                    loop recupero documenti di richiesta integrazione degli ET
                    F ->> B: request_instance_document(cui, resource_id)
                    note right of F: resource_id in integration_document_list
                    B -->> F: instanceDocument    
                    end
                end
                F -) P: notification(cui,integration_requested) 
                loop per ogni ente terzo interessato
                    B -->> E: notify(integration_requested)
                    E -->> B: ack
                end
                alt oltre il tempo di integrazione del presentatore
                    B ->> F: notify(cui, instance_descriptor_version, integration_response_time_expired)
                    F -->> B: ack
                    par per ogni ente terzo interessato
                        B ->> E: notify(cui, instance_descriptor_version, integration_response_time_expired)
                        E -->> B: ack
                    end
                    B ->> C: audit(cui, integration_response_time_expired)
                    C -->> B: ack

                    opt invio provvedimento finale per mancata integrazione
                        E ->> B: send_conclusions(NegativeOutcome)
                        B -->> E: ack 
                        E ->> C: audit(cui,negative_outcome_sended_from_<ET>)
                        C -->> E: ack
                        opt
                            B ->> E: request_instance_document(cui, resource_id)
                            note right of B: recupero documento di parere negativo
                            E -->> B: instanceDocument    
                        end 
                    end  

                    B ->> F: notify(cui, instance_descriptor_version, end_by_integration_time_expired)
                    F -) P: notification(cui, end_by_integration_time_expired)

                    par per ogni ente terzo interessato
                        B ->> E: notify(cui, instance_descriptor_version, end_by_integration_time_expired)
                        E -->> B: ack
                    end
                    B ->> C: audit(cui, end_by_integration_time_expired)
                    C -->> B: ack
                else entro il tempo di integrazione del presentatore 
                    P --) F: instanceIntegrated
                    F ->> B: send_instance_updated_documents(SendUpdatedDocuments)
                    B -->> F: ack
                    F ->> C: audit(cui,instance_integrated_to_<BO>_sended)
                    note right of F: <BO> codice BackOffice
                    C -->> F: ack
                    loop per ogni procedimento parte dell'istanza 
                        B ->> F: request_instance_document(cui, resource_id)
                        note left of B: resource_id da instance_index
                        F -->> B: instanceDocument
                    end
                    B ->> C: audit(cui,instance_integrated_retrived)
                    C -->> B: ack
                    B ->> C: update_attachments_and_times(cui,times,attachments,free_attachments)
                    Note right of B: Aggiorna i tempi procedimentali decrementandoli di X giorni, dove X è la differenza tra i giorni concessi per l'integrazione e i giorni passati dall'invio della richiesta
                    C -->> B: instanceDescriptor
                    par per ogni ente terzo interessato                
                        B ->> E: send_instance_updated_documents(SendUpdatedDocuments)
                        E -->> B: ack
                        B ->> C: audit(cui,instance_integrated_to_<ET>_sended)
                        note right of B: <ET> codice ente terzo
                        C -->> B: ack
                        loop per ogni procedimento di interesse parte dell'istanza 
                            E ->> B: request_instance_document(cui, resource_id)
                            note left of E: resource_id da instance_index
                            B -->> E: instanceDocument
                        end
                        E ->> C: audit(cui,instance_integrated_retrived_from_<ET>)
                        C -->> E: ack
                    end
                end
            end
            
            opt Regime Amministrativo=AUTORIZZAZIONE | L'ente terzo invia dei motivi ostativi
                E ->> B: send_impediments(Impediments)
                B -->> E: ack
                E ->> C: audit(cui, existence_of_impediments_from_<ET>, resource_id)
                C ->> E: ack
                B ->> E: request_instance_document(cui, resource_id)
                E ->> B: instanceDocument
                B ->> F: notify(cui, instance_descriptor_version,existence_of_impediments)
                F -->> B: ack
                B ->> C: audit(cui, impediments_received_from_<ET>, resource_id)
                C ->> B: ack
                B ->> C: request_update_times(cui, times)
                C ->> B: instanceDescriptor
                Note right of B: Aggiorna i tempi procedimentali incrementantoli di 10 giorni
                F ->> B: request_instance_document(cui, resource_id)
                B ->> F: instanceDocument
                F -) P: notification(cui,existence_of_impediments)
                alt osservazioni inviate nei tempi previsti (10 giorni)
                    P --) F: observations_to_impediments
                    F ->> B: notify(cui, instance_descriptor_version, observations_to_impediments_provided)
                    B -->> F: ack
                    F ->> C: audit(cui, observations_to_impediments_provided)
                    C -->> F: ack
                    B ->> C: request_update_times(cui, times)
                    C ->> B: instanceDescriptor
                    Note right of B: Aggiorna i tempi procedimentali decrementandoli dei giorni avanzati
                    B ->> F: request_instance_document(cui, resource_id)
                    F ->> B: instanceDocument
                    par Il BO notifica le osservazioni del presentatore a ogni ET che ha inviato i motivi ostativi
                        B ->> E: notify(cui, instance_descriptor_version, observations_to_impediments_provided, resource_id)
                        E -->> B: ack
                        B ->> C: audit(cui, observations_to_impediments_provided_to_<ET>)
                        C -->> B: ack
                        E ->> B: request_instance_document(cui, resource_id)
                        B ->> E: instanceDocument
                    end
                else osservazioni non inviate entro i tempi previsti (10 giorni)
                    par per ogni ET interessato
                        B ->> E: notify(cui, instance_descriptor_version,end_by_observations_time_expired)
                        E -->> B: ack
                    end
                    B ->> C: audit(cui, end_by_observations_request_time_expired)
                end
            end

            opt Regime Amministrativo=SCIA | almeno una richiesta conformazione
                par almeno un ente terzo
                    E ->> B: request_conformation(cui, instance_descriptor_version,conformation_list, conformation_document_list)
                    B -->> E: ack 
                    opt
                        B ->> E: request_instance_document(cui, resource_id)
                        note right of B: recupero documento di richiesta di conformazione
                        E -->> B: instanceDocument    
                    end
                    alt Aggiunti allegati non presenti nell'instance descriptor
                        E ->> C: audit(cui, conformation_requested_with_new_document_to_<Usecase_Proceding_Code>_from_<ET>)
                        C -->> E: ack
                    else
                        E ->> C: audit(cui,conformation_requested_from_<ET>)
                        C -->> E: ack  
                    end         
                end

            
                alt concluso il tempo di richiesta di conformazione 
                    par per ogni ente terzo
                        B ->> E: notify(cui, instance_descriptor_version, conformation_request_time_expired)
                        E -->> B: ack
                    end
                    B ->> C: audit(cui, conformation_request_time_expired)
                    C -->> B: ack
                end 
                
                Note over B: concluso il tempo di richiesta conformazione AND almeno un ente terzo ha richiesto la conformazione
                B ->> F: request_conformation(cui, instance_descriptor_version,conformation_list, conformation_document_list)
                F -->> B: ack
                alt Aggiunti allegati non presenti nell'instance descriptor
                    E ->> C: audit(cui, conformation_requested_with_new_document_to_<Usecase_Proceding_Code>)
                    C -->> E: ack
                else
                    B ->> C: audit(cui,conformation_requested)
                    C -->> B: ack
                end
                B ->> C: request_update_times(cui,times)
                Note right of B: Aggiorna i tempi procedimentali incrementandoli di X giorni, dove X è max_gg_conf_resp dell'oggetto Times
                C -->> B: instanceDescriptor
                opt
                    loop recupero documenti di richiesta di conformazione degli ET
                    F ->> B: request_instance_document(cui, resource_id)
                    note right of F: resource_id in conformation_document_list
                    B -->> F: instanceDocument    
                    end
                end
                F -) P: notification(cui,conformation_requested)    
                loop per ogni ente terzo interessato
                    B -->> E: notify(conformation_requested)
                    E -->> B: ack
                end

                alt oltre il tempo di conformazione del presentatore
                    B ->> F: notify(cui, instance_descriptor_version, conformation_response_time_expired)
                    F -->> B: ack
                    par per ogni ente terzo interessato
                        B ->> E: notify(cui, instance_descriptor_version, conformation_response_time_expired)
                        E -->> B: ack
                    end
                    B ->> C: audit(cui, conformation_response_time_expired)
                    C -->> B: ack

                    opt invio provvedimento finale per mancata conformazione
                        E ->> B: send_conclusions(NegativeOutcome)
                        B -->> E: ack 
                        E ->> C: audit(cui, suspension_requested_from_<ET>)
                        C -->> E: ack
                        opt
                            B ->> E: request_instance_document(cui, resource_id)
                            note right of B: recupero documento di richiesta sospensione
                            E -->> B: instanceDocument    
                        end 
                    end  

                    B ->> F: notify(cui, instance_descriptor_version, end_by_conformation_time_expired)
                    F -) P: notification(cui, end_by_conformation_time_expired)

                    par per ogni ente terzo interessato
                        B ->> E: notify(cui, instance_descriptor_version, end_by_conformation_time_expired)
                        E -->> B: ack
                    end
            B ->> C: audit(cui, end_by_conformation_time_expired)
                else entro il tempo di conformazione del presentatore 
                    P --) F: instanceConformated
                    F ->> B: send_instance_updated_documents(SendUpdatedDocuments)
                    B -->> F: ack
                    F ->> C: audit(cui,instance_conformated_to_<BO>_sended)
                    note right of F: <BO> codice BackOffice
                    C -->> F: ack
                    loop per ogni procedimento parte dell'istanza 
                        B ->> F: request_instance_document(cui, resource_id)
                        note left of B: resource_id da instance_index
                        F -->> B: instanceDocument
                    end
                    B ->> C: audit(cui,instance_conformated_retrived)
                    C -->> B: ack
                    B ->> C: update_attachments_and_times(cui,times,attachments,free_attachments)
                    Note right of B: Aggiorna i tempi procedimentali decrementandoli di X giorni, dove X è la differenza tra i giorni concessi per la conformazione e i giorni passati dall'invio della richiesta
                    C -->> B: instanceDescriptor
                    par per ogni ente terzo interessato                
                        B ->> E: send_instance_updated_documents(SendUpdatedDocuments)
                        E -->> B: ack
                        B ->> C: audit(cui,instance_conformated_to_<ET>_sended)
                        note right of B: <ET> codice ente terzo
                        C -->> B: ack
                        loop per ogni procedimento di interesse parte dell'istanza 
                            E ->> B: request_instance_document(cui, resource_id)
                            note left of E: resource_id da instance_index
                            B -->> E: instanceDocument
                        end
                        E ->> C: audit(cui,instance_conformated_retrived_from_<ET>)
                        C -->> E: ack
                    end

                end

            end

            alt Regime Amministrativo=AUTORIZZAZIONE | integrazione non richiesta, oppure richiesta e istanza integrata nei tempi dal presentatore
                par
                    opt se non si applica silenzio assenso
                        alt parere esplicito positivo
                            E ->> B: send_conclusions(PositiveOutcome)
                            B -->> E: ack 
                            E ->> C: audit(cui,positive_outcome_sended_from_<ET>)
                            C -->> E: ack
                            opt
                                B ->> E: request_instance_document(cui, resource_id)
                                note right of B: recupero documento di parere positivo
                                E -->> B: instanceDocument    
                            end
                        else parere esplicito negativo
                            E ->> B: send_conclusions(NegativeOutcomeRequired)
                            B -->> E: ack 
                            E ->> C: audit(cui,negative_outcome_sended_from_<ET>)
                            C -->> E: ack
                            opt
                                B ->> E: request_instance_document(cui, resource_id)
                                note right of B: recupero documento di parere negativo
                                E -->> B: instanceDocument    
                            end
                        end
                    end       
                end
 
                Note over B,E: concluso tempo ricezione pareri o tutti gli ET hanno inviato parere (compreso silenzio assenso)
                opt Regime Amministrativo=AUTORIZZAZIONE | CdSS da SUAP
                    opt 
                        B ->> C: request_update_times(cui,times)
                        C -->> B: instanceDescriptor
                    end 
                    B ->> F: notify(cui, instance_descriptor_version,cdss_convened)
                    F -->> B: ack    
                    par per ogni ente terzo interessato
                        B ->> E: notify(cui, instance_descriptor_version,cdss_convened)
                        E -->> B: ack
                    end
                    
                    B ->> C: audit(cui,cdss_convened)
                    C -->> B: ack
                end            
            end

            alt Regime Amministrativo=SCIA | conformazione non richiesta, oppure richiesta e istanza conformata nei tempi dal presentatore
                par
                    alt ET esprime parere negativo
                        E ->> B: send_conclusions(NegativeOutcomeRequired)
                        B -->> E: ack 
                        E ->> C: audit(cui,suspension_requested_from_<ET>)
                        C -->> E: ack
                        opt
                            B ->> E: request_instance_document(cui, resource_id)
                            note right of B: recupero documento di richiesta sospensione
                            E -->> B: instanceDocument    
                        end   
                    end       
                end

                alt concluso tempo istanza, senza richieste sospensione
                    B ->> F: notify(cui, instance_descriptor_version,end_by_proceeding_time_expired)
                    F -->> B: ack            
                    par per ogni ente terzo interessato
                        B ->> E: notify(cui, instance_descriptor_version,end_by_proceeding_time_expired)
                        E -->> B: ack
                    end
                    B ->> C: audit(cui,end_by_proceeding_time_expired)
                    C -->> B: ack
                else concluso tempo istanza o tutti gli enti terzi hanno inoltrato conclusione, almeno una richiesta sospensione
                    B ->> F: notify(cui, instance_descriptor_version,end_by_suspension_requested)
                    F -->> B: ack  
                    F -) P: notification(cui,end_by_suspension_requested)          
                    par per ogni ente terzo interessato
                        B ->> E: notify(cui, instance_descriptor_version,end_by_suspension_requested)
                        E -->> B: ack
                    end
                    B ->> C: audit(cui,end_by_suspension_requested)
                    C -->> B: ack
                end


            end


    end
    Note over F, E: Regime Amministrativo=AUTORIZZAZIONE | azione realizzata in ogni circostanza, anche in caso di CdSS
    alt Regime Amministrativo=AUTORIZZAZIONE | (concluso tempo istanza (eventuale silenzio assenso) o autorizzazione concessa) e integrazione del presentatore nei tempi 
        B ->> C: add_permit_document(cui, permit_document)
        C -->> B: ack
        B ->> F: notify(cui, instance_descriptor_version,end_by_positive_outcome,resource_id)
        F -->> B: ack
        F ->> B: request_instance_document(cui, resource_id)
        note right of F: recupero documento di provvedimento di autorizzazione
        B -->> F: instanceDocument  
        F -) P: notification(cui,end_by_positive_outcome)   
        opt se non si è tenuta la CdSS       
            par per ogni ente terzo interessato
                B ->> E: notify(cui, instance_descriptor_version,end_by_positive_outcome,resource_id)
                E -->> B: ack
                E ->> B: request_instance_document(cui, resource_id)
            note right of B: recupero documento di provvedimento di autorizzazione
                B -->> E: instanceDocument 
            end
        end
        B ->> C: audit(cui,end_by_positive_outcome)
        C -->> B: ack
    else Regime Amministrativo=AUTORIZZAZIONE | autorizzazione negata OR osservazioni ai motivi ostativi non inviate dal presentatore nei tempi (10 giorni)
        B ->> F: notify(cui, instance_descriptor_version,end_by_negative_outcome,resource_id)
        F -->> B: ack
        F ->> B: request_instance_document(cui, resource_id)
        note right of F: recupero documento di negazione provvedimento di autorizzazione
        B -->> F: instanceDocument      
        F -) P: notification(cui,end_by_negative_outcome)    
        opt se non si è tenuta la CdSS       
            par per ogni ente terzo interessato
                B ->> E: notify(cui, instance_descriptor_version,end_by_negative_outcome,resource_id)
                E -->> B: ack
                E ->> B: request_instance_document(cui, resource_id)
            note right of B: recupero documento di negazione provvedimento di autorizzazione
                B -->> E: instanceDocument 
            end
        end
        B ->> C: audit(cui,end_by_negative_outcome)
        C -->> B: ack
    end
end