sequenceDiagram
    autonumber

    actor P as Presentatore    
    participant F as FrontOffice SUAP
    participant B as BackOffice SUAP   
    participant C as Catalogo SSU 
    participant E as Enti Terzi    

    Note over F,B: istanza procedibile

    
    par per ogni ente terzo interessato        
        B ->> E: send_instance(SendInstanceRequest)
        E -->> B: ack
        B ->> C: audit(cui,instance_to_<ET>_sended)
        note right of B: <ET> codice ente terzo 
        C -->> B: ack
        E ->> C: request_instance_descriptor(cui)
        C -->> E: instanceDescriptor
        loop per ogni procedimento di interesse parte dell'istanza 
        E ->> B: request_instance_document(cui, resource_id)
        note left of E: resource_id da instance_index
        B -->> E: instanceDocument
        end
        E ->> C: audit(cui,instance_retrived)
        C -->> E: ack
    end

    opt almeno una richiesta integrazione
        par almeno un ente terzo
            E ->> B: request_integration(cui, instance_descriptor_version,integration_list,resource_id)
            B -->> E: ack 
            opt
                B ->> E: request_instance_document(cui, resource_id)
                note right of B: recupero documento di richiesta integrazione
                E -->> B: instanceDocument    
            end
            E ->> C: audit(cui,integration_requested)
            C -->> E: ack           
        end

      
		alt concluso il tempo di richiesta integrazione 
			par per ogni ente terzo
				B ->> E: notify(cui, instance_descriptor_version, integration_request_time_expired)
				E -->> B: ack
			end
			B ->> C: audit(cui, integration_request_time_expired)
			C -->> B: ack
		end 
		
		Note over B: concluso il tempo di richiesta integrazione OR tutti gli enti terzi hanno richiesto integrazione
        B ->> F: request_integration(cui, instance_descriptor_version,list_of_integration_list,integration_document_list)
        F -->> B: ack
        B ->> C: audit(cui,integration_requested)
        C -->> B: ack
        opt
            loop recupero documenti di richiesta integrazione degli ET
            F ->> B: request_instance_document(cui, resource_id)
            note right of F: resource_id in integration_document_list
            B -->> F: instanceDocument    
            end
        end
        F -) P: notification(cui,integration_requested)    


        alt oltre il tempo di integrazione del presentatore
            B ->> F: notify(cui, instance_descriptor_version,end_by_integration_times_expired)
            F -->> B: ack
            par per ogni ente terzo interessato
                B ->> E: notify(cui, instance_descriptor_version,end_by_integration_times_expired)
                E -->> B: ack
            end
            B ->> C: audit(cui,end_by_integration_request_time_expired)
            C -->> B: ack

            F -) P: notification(cui,end_by_integration_times_expired)
        else entro il tempo di integrazione del presentatore 
            P --) F: instanceIntegrated
            F ->> B: send_instance(SendInstanceRequest)
            B -->> F: ack
            F ->> C: audit(cui,instance_integrated_to_<BO>_sended)
            note right of F: <BO> codice BackOffice
            C -->> F: ack
            loop per ogni procedimento parte dell'istanza 
                B ->> F: request_instance_document(cui, resource_id)
                note left of B: resource_id da instance_index
                F -->> B: instanceDocument
            end
            B ->> C: audit(cui,instance_integrated_retrived)
            C -->> B: ack
            par per ogni ente terzo interessato                
                B ->> E: send_instance(SendInstanceRequest)
                E -->> B: ack
                B ->> C: audit(cui,instance_integrated_to_<ET>_sended)
                note right of B: <ET> codice ente terzo
                C -->> B: ack
                loop per ogni procedimento di interesse parte dell'istanza 
                    E ->> B: request_instance_document(cui, resource_id)
                    note left of E: resource_id da instance_index
                    B -->> E: instanceDocument
                end
                E ->> C: audit(cui,instance_integrated_retrived)
                C -->> E: ack
            end

        end

    end
    
    alt integrazione non richiesta, oppure richiesta e istanza integrata nei tempi dal presentatore

        par
            alt 
                E ->> B: send_conclusions(NegativeOutcomeRequired)
                B -->> E: ack 
                E ->> C: audit(cui,suspension_requested)
                C -->> E: ack
                opt
                    B ->> E: request_instance_document(cui, resource_id)
                    note right of B: recupero documento di richiesta sospensione
                    E -->> B: instanceDocument    
                end  
                
            else
                E ->> B: send_conclusions(ConformationRequired)
                B -->> E: ack 
                E ->> C: audit(cui,conformation_requested)
                C -->> E: ack 
                opt
                    B ->> E: request_instance_document(cui, resource_id)
                    note right of B: recupero documento di richiesta conformazione
                    E -->> B: instanceDocument    
                end  
            end       
        end

        alt concluso tempo istanza, senza richieste sospensione/conformazione
            B ->> F: notify(cui, instance_descriptor_version,end_by_proceeding_time_expired)
            F -->> B: ack            
            par per ogni ente terzo interessato
                B ->> E: notify(cui, instance_descriptor_version,end_by_proceeding_time_expired)
                E -->> B: ack
            end
            B ->> C: audit(cui,end_by_proceeding_time_expired)
            C -->> B: ack
        else concluso tempo istanza o tutti gli enti terzi hanno inoltrato conclusione, almeno una richiesta sospensione
            B ->> F: notify(cui, instance_descriptor_version,end_by_suspension_requested)
            F -->> B: ack  
            F -) P: notification(cui,end_by_suspension_requested)          
            par per ogni ente terzo interessato
                B ->> E: notify(cui, instance_descriptor_version,end_by_suspension_requested)
                E -->> B: ack
            end
            B ->> C: audit(cui,end_by_suspension_requested)
            C -->> B: ack
        else concluso tempo istanza o tutti gli enti terzi hanno inoltrato conclusione, nessuna richiesta sospesione,almeno una richiesta conformazione
            B ->> F: notify(cui, instance_descriptor_version,end_by_conformation_requested)
            F -->> B: ack
            F -) P: notification(cui,end_by_conformation_requested)               
            par per ogni ente terzo interessato
                B ->> E: notify(cui, instance_descriptor_version,end_by_conformation_requested)
                E -->> B: ack
            end
            B ->> C: audit(cui,end_by_conformation_requested)
            C -->> B: ack
        end


    end

   
